---

name: AutoLint

on:
  push:
    branches: [latest]
  pull_request:
    branches: [latest]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.10]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
